### ISSUE TITLE
the secret of 43

### ISSUE THREAD

**Issue by croissantderp** [croissantderp/geckobot#5]
DailyDM sends a large number of messages for some reason

### the main issue fix:
https://github.com/croissantderp/geckobot/blob/7aa9e26ddb78ebc9bdea7d07c7177d2fb0489630/Commands/DailyDM.cs#L431
add an id-specific singleton to ensure that the program only sends the daily message once to every user

### other issues to fix
https://github.com/croissantderp/geckobot/blob/7aa9e26ddb78ebc9bdea7d07c7177d2fb0489630/Commands/DailyDM.cs#L298
make all fields other than `bool yes` optional and default to 12:00:00 UTC and year 1

https://github.com/croissantderp/geckobot/blob/7aa9e26ddb78ebc9bdea7d07c7177d2fb0489630/Commands/DailyDM.cs#L368
make all fields other than `bool join` optional and default to 12:00:00 UTC and year 1

also, consider renaming the two commands above to something more intuitive and rewriting messages

https://github.com/croissantderp/geckobot/blob/7aa9e26ddb78ebc9bdea7d07c7177d2fb0489630/Commands/DailyDM.cs#L436-L449
remove this from `runChecks`, move to `checkProfile`

https://github.com/croissantderp/geckobot/blob/7aa9e26ddb78ebc9bdea7d07c7177d2fb0489630/Commands/DailyDM.cs#L365-L417
add sign up message and unsign up message

https://github.com/croissantderp/geckobot/blob/7aa9e26ddb78ebc9bdea7d07c7177d2fb0489630/Commands/Edit.cs
this is broken, discord changed something

remove empty values from array parser in math module

### future projects
gecko slot machine
retirement and merging of unnecessary modules (e.g. edit, prefix, music, embed, bugs)
retirement of unused commands (e.g. coin flip)
refactoring of certain commands to make it more intuitive (e.g. time parsing)

https://github.com/croissantderp/geckobot/blob/7aa9e26ddb78ebc9bdea7d07c7177d2fb0489630/Commands/Help.cs#L210
get build time using https://stackoverflow.com/questions/1600962/displaying-the-build-date

**Comment by ky28059** [comment]
frightening
